### ISSUE TITLE
关于tswkai在使用tab查看信息时鼠标只能放在主游戏区域内的问题

### ISSUE THREAD

**Issue by Sucaiking** [Z-H-Sun/tswKai#1]
一旦按下tab查看怪物信息，鼠标就会自动移动到主窗口，也就是11*11的区域中。
请问这是刻意为之，还是一个bug？

**Comment by Z-H-Sun** [comment]
刻意为之，防止用户在按下TAB时误用鼠标单击其他区域造成更严重的bug
